class AppData {
  static List<String> imgs = [
    "https://images.ctfassets.net/denf86kkcx7r/4IPlg4Qazd4sFRuCUHIJ1T/f6c71da7eec727babcd554d843a528b8/gatocomuneuropeo-97",
    "https://cdn.sanity.io/images/5vm5yn1d/pro/41c7e7ce298604b0801fc2b1b76371a47e9ebb83-950x633.jpg?fm=webp&q=80",
    "https://animalcity.es/clinica/wp-content/uploads/2021/08/Gatito-tumbado-min.jpg",
    "https://nutrisourcepetfoods.com/wp-content/uploads/2020/03/shutterstock_67901620-1000x600sfw-1.jpg",
    "https://urgenciesveterinaries.com/wp-content/uploads/2023/09/survet-gato-caida-pelo-01.jpeg",
    "https://www.mirringo.com.co/Portals/mirringo/Images/articulos-actualidad-gatuna/ciclo-de-vida-de-los-gatos/Interna-1-ciclo-de-vida-de-los-gatos.jpg?ver=2024-03-20-160432-910",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/250px-Cat_November_2010-1a.jpg",
    "https://static.nationalgeographicla.com/files/styles/image_3200/public/nationalgeographic_1468962.jpg?w=1900&h=1400",
    "https://cdn.royalcanin-weshare-online.io/tlYzqG0BBKJuub5qNVnB/v1/67-es-l-cat-in-a-sofa-thinking-getting-dog-gato-adecuado",
    "https://www.zooplus.es/magazine/wp-content/uploads/2020/10/Gatos-y-roedores-juntos.webp",
    "https://media.istockphoto.com/id/1160866353/photo/crop-hands-with-controller.jpg?s=612x612&w=0&k=20&c=ncOO3s1WfyGNM9dko0GHcqTvjl4sz8dl94o-_C4nir0=",
    "https://media.istockphoto.com/id/1334436084/photo/top-down-view-of-colorful-illuminated-gaming-accessories-laying-on-table.jpg?s=612x612&w=0&k=20&c=E9xnbAZoBS5LlUX0q-zxT_3m6gEZpyB2k51_U4LLMNs=",
    "https://t4.ftcdn.net/jpg/02/43/39/69/360_F_243396970_Mvx4h3Z8BGE3MIqjKZj4L4GJ5P5Y29FF.jpg",
    "https://media.istockphoto.com/id/1252455620/photo/golden-retriever-dog.jpg?s=612x612&w=0&k=20&c=3KhqrRiCyZo-RWUeWihuJ5n-qRH1MfvEboFpf5PvKFg=",
    "https://media.istockphoto.com/id/1503385646/photo/portrait-funny-and-happy-shiba-inu-puppy-dog-peeking-out-from-behind-a-blue-banner-isolated.jpg?s=612x612&w=0&k=20&c=xZq8PhunL9ZmY243et3GOf04wJPBmHzeiQ3jw7nWCrY=",
    "https://t3.ftcdn.net/jpg/00/65/76/24/360_F_65762430_bLbrz7wDChm8kT8OEYUpUFMdiLB2AM4b.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZCpt9R0oqB1CJTdjt6v1nOJLUkunmPacIOQ&s",
    "https://blueprintdigital.com/wp-content/uploads/2014/11/stock-photo-happy-man-giving-okay-sign-portrait-on-white-background-141327337.jpg",
    "https://cdn.expertphotography.com/wp-content/uploads/2019/03/yns-plt-527773-unsplash-1.jpg",
    "https://www.adobe.com/creativecloud/photography/discover/media_131179edca5f92db203e2b78cb8a308605afbc958.png?width=750&format=png&optimize=medium",
    "https://shotkit.com/wp-content/uploads/bb-plugin/cache/5aaa1cc4c422b-funny-weird-wtf-stock-photos-28-5a3a5b135f099__700-landscape-53b2b5789c8885ff7b66fb69338c8591-zybravgx2q47.jpg",
    "https://images.pexels.com/photos/13041008/pexels-photo-13041008.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyHqPwMFa5iLAAzWIe9-4f17IILpM4PIERbg&s",
    "https://media.istockphoto.com/id/187722063/photo/funny-man-with-watermelon-helmet-and-goggles.jpg?s=612x612&w=0&k=20&c=gRAm8vtLqdOU8a-mJVt6m_Wnv8pLpa3TBh2vRQP4208=",
    "https://i.pinimg.com/736x/00/50/0c/00500c37f0905f696529ea6ad4e4fc1a.jpg",
    "https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fl81zgr8qqg381.jpg%3Fwidth%3D640%26crop%3Dsmart%26auto%3Dwebp%26s%3D872b3052ee50b3938bd255376d111ac35d4a5d37",
    "https://thumbs.dreamstime.com/b/funny-man-big-fists-ready-fight-isolated-white-background-52211523.jpg",
  ];

  static List<String> titles = [
    'Mi gato juzgándome a las 3 de la mañana',
    'Cuando dices “solo una foto” y salen 20',
    'Este post no tiene imagen (imagina un gato)',
    'Gato durmiendo como si pagara el alquiler',
    'Intenté trabajar, pero mi gato tenía otros planes',
    'Foto borrosa de un gato que se movió',
    'Post serio sin imagen. O eso dice el título',
    'Gato mirando a la nada durante 10 minutos',
    'Hoy no hay imagen, pero ayer sí hubo gato',
    'Gato en una caja que claramente es demasiado pequeña',
    'Reflexiones profundas mientras un gato me observa',
    'Imagen adjunta: gato. Sorpresa: ninguna',
    'Mi gato ha decidido que este es su sofá',
    'Hoy iba a ser productivo hasta que apareció el gato',
    'Post sin imagen porque el gato se fue',
    'Gato observando el vacío como si entendiera el universo',
    'Intento de foto artística interrumpido por un gato',
    'Este contenido no tiene imagen, pero tiene gato espiritual',
    'Gato dormido en una postura legalmente imposible',
    'Pensamientos profundos mientras un gato me ignora',
    'Imagen no disponible: el gato tenía prisa',
    'Gato mirando por la ventana como protagonista de un drama',
    'Hoy no hay foto, pero el gato estuvo aquí',
    'Gato ocupando el sitio exacto que necesitaba',
    'Post serio hasta que apareció un gato',
    'Gato analizando si mereces su atención',
    'Sin imagen. Con dignidad. Y con gato.',
    'Gato durmiendo como si mañana tuviera que madrugar',
    'Reflexión importante interrumpida por un maullido',
    'Gato sentado encima del teclado. Otra vez.',
    'Este post no tiene foto, pero tiene supervisión felina',
    'Gato mirando la cámara con evidente superioridad',
    'Un día normal que acabó siendo interesante',
    'A veces las cosas salen mejor sin planearlas',
    'Hoy tocaba hacer esto, y se hizo',
    'Pequeños detalles que pasan desapercibidos',
    'No era la idea inicial, pero funcionó',
    'Momentos simples que merecen ser contados',
    'Cuando paras un segundo y miras alrededor',
    'Nada extraordinario, pero digno de recordarse',
    'Una decisión pequeña con consecuencias curiosas',
    'Hoy no hay imagen, solo contexto',
    'Pensamientos sueltos de un día cualquiera',
    'Esto empezó como algo rápido y se alargó',
    'A veces menos es exactamente suficiente',
    'No todo tiene que tener una explicación',
    'Un recordatorio de por qué hacemos las cosas así',
    'Cosas que no planeas, pero agradeces',
    'Un momento tranquilo en medio del ruido',
    'Hoy tocó improvisar',
    'Reflexiones que llegan sin avisar',
    'Nada épico, pero auténtico',
  ];
}